import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { spawnSync } from "node:child_process";
import { fileURLToPath } from "node:url";

const projectRoot = resolve(process.cwd());
const webRoot = resolve(projectRoot, "web");
const outputDir = resolve(projectRoot, "dist/web");
const bundleDir = resolve(projectRoot, ".generated");
const bundleFile = resolve(bundleDir, "web-bundle.ts");

function serialize(value) {
  return JSON.stringify(value)
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

function runVite() {
  const result = spawnSync("vite", ["build", "--config", resolve(webRoot, "vite.config.ts")], {
    cwd: projectRoot,
    env: process.env,
    stdio: "inherit"
  });
  if (result.error) throw result.error;
  if (result.status !== 0) throw new Error(`Vite 构建失败（退出码 ${String(result.status)}）`);
}

export function prepareUi() {
  runVite();
  const htmlFile = resolve(outputDir, "index.html");
  const scriptFile = resolve(outputDir, "gateway.js");
  const styleFile = resolve(outputDir, "gateway.css");
  for (const file of [htmlFile, scriptFile, styleFile]) {
    if (!existsSync(file)) throw new Error(`Web UI 构建产物缺失: ${file}`);
  }

  const script = readFileSync(scriptFile, "utf8").replace(/<\/script/gi, "<\\/script");
  const style = readFileSync(styleFile, "utf8").replace(/<\/style/gi, "<\\/style");
  const title = readFileSync(htmlFile, "utf8").match(/<title>(.*?)<\/title>/s)?.[1] ?? "LLM Gateway";
  const document = `<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#090d18" />
    <title>${title}</title>
    <style>${style}</style>
  </head>
  <body>
    <div id="root"></div>
    <script>${script}</script>
  </body>
</html>`;

  mkdirSync(bundleDir, { recursive: true });
  writeFileSync(
    bundleFile,
    [
      "// Generated by scripts/prepare-ui.mjs. Do not edit manually.",
      `export const WEB_UI_HTML = ${serialize(document)};`,
      ""
    ].join("\n")
  );
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  prepareUi();
}
