import { existsSync } from "node:fs";

import { getAuthStore } from "./auth-store.js";
import { loadConfig, type GatewayConfig } from "./config.js";
import { getModels } from "./models.js";
import { modelsResponse } from "./openai.js";
import { getProviders } from "./provider.js";
import type { ModelDescriptor, ReasoningEfforts } from "./types.js";

function quote(value: string): string {
  return JSON.stringify(value);
}

function formatTime(value: number | null): string {
  if (!value) return "未认证";
  return new Date(value).toLocaleString("zh-CN", {
    dateStyle: "short",
    timeStyle: "medium"
  });
}

function formatEndpoint(config: GatewayConfig): string {
  const host = config.bindHost === "0.0.0.0" || config.bindHost === "::"
    ? "127.0.0.1"
    : config.bindHost;
  return `http://${host}:${config.port}`;
}

function effortEntries(efforts: ReasoningEfforts): string[] {
  return Object.entries(efforts).map(([name, wireValue]) => {
    const key = /^[a-zA-Z0-9_-]+$/.test(name) ? name : quote(name);
    return wireValue === null
      ? `            ${key}:`
      : `            ${key}: ${quote(wireValue)}`;
  });
}

function modelConfigLines(model: ModelDescriptor): string[] {
  const id = model.publicId ?? model.id;
  const lines = [`        - id: ${quote(id)}`];
  if (model.name) lines.push(`          name: ${quote(model.name)}`);
  if (model.maxInputTokens) {
    lines.push(`          contextWindow: ${String(model.maxInputTokens)}`);
  }
  if (model.maxOutputTokens) {
    lines.push(`          maxTokens: ${String(model.maxOutputTokens)}`);
  }
  if (model.reasoningEfforts) {
    lines.push("          reasoningEfforts:");
    lines.push(...effortEntries(model.reasoningEfforts));
  }
  return lines;
}

function harnessConfig(models: ModelDescriptor[], config: GatewayConfig): string {
  const defaults = models
    .map((model) => model.defaultReasoningEffort)
    .filter((value): value is string => Boolean(value));
  const commonDefault = defaults.length > 0 &&
    defaults.every((value) => value === defaults[0])
    ? defaults[0]
    : undefined;
  const lines = [
    "# Generated by llm-gateway export deepseek-harness",
    "# The gateway owns provider routing; this is the only endpoint Harness needs.",
    "llm-pi-ai:",
    "  providers:",
    "    llm-gateway:",
    "      api: openai-completions",
    `      baseURL: ${quote(formatEndpoint(config) + "/v1")}`,
    "      compat:",
    "        thinkingFormat: deepseek",
    "        supportsReasoningEffort: true",
    "        supportsDeveloperRole: false"
  ];
  if (commonDefault) lines.push(`      reasoning: ${quote(commonDefault)}`);
  lines.push("      models:");

  if (models.length === 0) {
    lines.push("        # No models discovered. Run authentication, then retry.");
  } else {
    for (const model of models) lines.push(...modelConfigLines(model));
  }

  return lines.join("\n") + "\n";
}

export async function printModels(): Promise<void> {
  const config = loadConfig();
  const models = await getModels(config);
  console.log(JSON.stringify(modelsResponse(models), null, 2));
}

export async function exportDeepSeekHarness(): Promise<void> {
  const config = loadConfig();
  const models = (await getModels(config)).filter(
    (model) => model.capabilities?.chat !== false
  );
  process.stdout.write(harnessConfig(models, config));
}

export async function runDoctor(): Promise<number> {
  const config = loadConfig();
  const providers = getProviders();
  const auth = getAuthStore(config).status(providers.map((provider) => provider.id));
  const models = await getModels(config);
  const endpoint = formatEndpoint(config);
  const issues: string[] = [];

  console.log("LLM Gateway doctor");
  console.log(`  endpoint: ${endpoint}`);
  console.log(`  runtime:  ${config.runtimeDir}`);
  console.log(`  auth:     ${config.authCacheDir}`);
  console.log("");
  console.log("Providers:");

  for (const provider of providers) {
    const status = auth.providers[provider.id];
    const cacheFile = `${config.authCacheDir}/${provider.id}.json`;
    const ready = status?.ready === true;
    console.log(
      `  ${ready ? "✓" : "!"} ${provider.name} (${provider.id})` +
      ` · ${ready ? "已认证" : "未认证"}` +
      ` · ${formatTime(status?.capturedAt ?? null)}`
    );
    if (!ready) {
      issues.push(`${provider.id} 未认证`);
      console.log(`      执行: npm run auth -- --provider ${provider.id}`);
    } else if (!existsSync(cacheFile)) {
      issues.push(`${provider.id} 缓存不可读`);
    }
  }

  console.log("");
  console.log(`Models:   ${models.length} discovered`);
  if (models.length === 0) issues.push("没有可用模型");
  console.log(`Result:   ${issues.length === 0 ? "ready" : "需要处理"}`);
  for (const issue of issues) console.log(`  - ${issue}`);
  return issues.length === 0 ? 0 : 1;
}
